
media:
  input: public/assets
  output: /assets
  categories: [ "image" ]
content:
  - name: home
    label: Home
    type: file
    path: _home.yml
    fields:
      - name: title
        label: Title
        type: string
      - name: subtitle
        label: Subtitle
        type: string
      - name: description
        label: Description
        type: string
      - name: next_meetup_0
        label: Next meetup header
        type: string  
      - name: next_meetup_1
        label: Next meetup line 1
        type: string  
      - name: next_meetup_2
        label: Next meetup line 2
        type: string  
      - name: next_meetup_3
        label: Next meetup line 3
        type: string  
      - name: isFlashy
        label: Flashy
        type: boolean
        default: true
      - name: mail_button
        label: Mail button
        type: string  

  - name: _meetups
    label: Meetups
    type: collection
    path: _meetups
    view:
      fields: [ title ]
    fields:
      - { name: title, label: Title, type: string}
      - { name: subtitle, label: Subtitle, type: string}
      - { name: description, label: Description, type: string}
      - { name: when_where, label: When & Where, type: string}
      - { name: schedule, label: Schedule, type: string}
      - name: Speaker
        label: Speaker
        type: object
        fields:
          - { name: name, label: Name, type: string }
          - { name: picture, label: Picture, type: image }
          - { name: bio, label: Bio, type: string }
          - { name: link1, label: Link 1, type: string }
          - { name: link2, label: Link 2, type: string }